# Generated by Django 2.2 on 2019-04-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20190429_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jo',
            name='document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='jo',
            name='gender',
            field=models.CharField(default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='gender',
            field=models.CharField(default='M', max_length=2),
        ),
    ]
